app/views/layouts/application.html.erb
J'ai supprimé le tag qui fait chier a cause de rails 6 (la bombe !!!)
=> JS tag delete

app/controllers/dashboards_controller.rb, app/controllers/rentals_controller.rb, app/controllers/users_controller.rb, app/controllers/vans_controller.rb, app/views/rentals/create.html.erb, app/views/rentals/new.html.erb, app/views/vans/create.html.erb, app/views/vans/new.html.erb, app/views/vans/search.html.erb, app/views/vans/show.html.erb, config/routes.rb, test/controllers/dashboards_controller_test.rb, test/controllers/rentals_controller_test.rb, test/controllers/users_controller_test.rb, test/controllers/vans_controller_test.rb
=> ajout des controllers et des routes

app/controllers/vans_controller.rb, app/models/van.rb, app/views/vans/show.html.erb
=> Van controller

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/vans/search.html.erb
petite modif home et components Card/banner
=> petite modif home et components Card/banner

app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss
=> css-config color + font

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_home.scss, app/views/vans/search.html.erb
=> nom de class css

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/views/vans/search.html.erb
=> homepage nicer Card + form

app/controllers/dashboards_controller.rb, app/controllers/rentals_controller.rb, app/controllers/vans_controller.rb
Maj des trois controlleurs vans, dashboard, rentals avec le squelette des méthodes
=> Controllers

app/views/vans/search.html.erb
=> photo change

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/vans/_new.scss, app/views/vans/_form.html.erb, config/initializers/simple_form_bootstrap.rb
Component bouton avec la classe SCSS
=> bouton create back ok

.gitignore, app/models/van.rb, app/views/dashboards/index.html.erb, app/views/vans/index.html.erb
=> upload/ views picture

db/schema.rb, db/seeds.rb
modif des seeds : ville = Vannes, 
ajout d'un van
=> modif des seeds : ville = Vannes, ajout d'un van

db/seeds.rb
ai raccourci la description d'une seed
ai validé que l'index des vans est accessible sans authent
=> ai raccourci la description d'une seed

app/assets/stylesheets/pages/vans/_new.scss, app/views/vans/_form.html.erb, app/views/vans/new.html.erb
Modifié le titre sur la bannière et redimensionnement du formulaire
=> Modifie titre et Form du van/new

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/vans/_index.scss
=> footer margin

app/assets/stylesheets/pages/_index.scss
=> dashboard index reorga

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/users/_index.scss, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
=> sign-in page

app/assets/stylesheets/components/_footer.scss
=> taille footer

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/users/_registration.scss, app/views/devise/registrations/new.html.erb
Signup button + emojii user/signup
=> Signup button

app/assets/stylesheets/pages/Dashboard/_index.scss, app/controllers/dashboards_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/dashboards/_no_owner.html.erb, app/views/dashboards/_owner.html.erb, app/views/dashboards/index.html.erb
"dashboard owner done et dynamique"
=> Dashindex2

app/controllers/dashboards_controller.rb, app/models/van.rb, app/views/dashboards/_owner.html.erb
=> imùage dynamique par defaut

app/assets/stylesheets/pages/Dashboard/_index.scss
=> bug fix merge Hugo/marin

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/pages/_show.scss, app/views/vans/show.html.erb
=> page show fixed
